services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./backend/media:/vol/web/media
    command: >
      sh -c "python /app/backend/manage.py wait_for_db &&
                   python /app/backend/manage.py migrate &&             
                   python /app/backend/manage.py loaddata sample_cinema.json &&
                   python /app/backend/manage.py runserver 0.0.0.0:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env